cabal-version: 3.0
name: todo-app
version: 0.1.0.0
build-type: Simple

common defaults
  ghc-options: -Wall
  build-depends:
    base,
    relude,

  default-extensions:
    OverloadedStrings

  default-language: Haskell2010
  mixins:
    base hiding (Prelude),
    relude (Relude as Prelude),
    relude,

library
  import: defaults
  hs-source-dirs: src
  exposed-modules:
    Website
    Website.Files
    Website.Page
    Website.Page.About
    Website.Page.Contact
    Website.Page.Home
    Website.Site

  build-depends:
    blaze-html,
    directory,
    filepath,

executable backend
  import: defaults
  hs-source-dirs: app/backend
  main-is: Main.hs

executable website
  import: defaults
  hs-source-dirs: app/website
  main-is: Main.hs
  build-depends:
    todo-app

  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N
